[package]
name = "sausage_solver"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"

[dependencies]
brutalize = { path = "../brutalize" }
solver_common = { path = "../solver_common" }
smallvec = "1.4"